name: wheather_app
description: "Weather App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  http: ^1.2.2
  provider: ^6.1.2
  lottie: ^3.2.0
  geolocator: ^13.0.2
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.10.0
  flutter_riverpod: ^2.6.1
  jiffy: ^6.3.2
  dio: ^5.7.0
  responsive_builder: ^0.7.1
  weather_animation: ^1.1.1
  animations: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - .env.development
    - assets/icons/
